version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped

  frontend:
    build: ../frontend
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    external:
      name: dailytracker-net
